# Generated by Django 6.1.1 on 2026-09-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={'verbose_name': 'Despacho', 'verbose_name_plural': 'Despachos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name': 'Recepción', 'verbose_name_plural': 'Recepciones'},
        ),
    ]
