# Generated by Django 6.1.1 on 2026-09-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_alter_almacen_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recepcion',
            options={},
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='longitud',
        ),
        migrations.AlterField(
            model_name='despacho',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='modulo_asignado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
    ]
