# Generated by Django 6.1.1 on 2026-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_alter_almacen_options_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={'verbose_name': 'Despacho', 'verbose_name_plural': 'Despachos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name': 'Recepción', 'verbose_name_plural': 'Recepciones'},
        ),
        migrations.AddField(
            model_name='despacho',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='destino',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='modulo_asignado',
            field=models.CharField(choices=[('catalogo', 'Catálogo'), ('almacen', 'Almacén'), ('inventario', 'Inventario'), ('recepcion', 'Recepción'), ('despacho', 'Despacho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='proveedor',
            field=models.CharField(max_length=150),
        ),
    ]
