"""
Django settings for logicore_core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!dau3tno&=z5l4mo*g6@u6$u+pf4a#07#$6bca4xzo#4hw2j4a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['logicore-wms.onrender.com', '.onrender.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modulo',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'logicore_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'modulo' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'logicore_core.wsgi.application'


# Database
# https://djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'modulo' / 'static',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Email
# https://djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Jazzmin Customization for LogiCore UPEC
JAZZMIN_SETTINGS = {
    "site_title": "LogiCore UPEC WMS",
    "site_header": "LogiCore UPEC",
    "site_brand": "LogiCore UPEC",
    "welcome_sign": "Bienvenido al Sistema de Gestión de Almacenes - UPEC",
    "copyright": "LogiCore UPEC - Ecuador",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "modulo.almacen": "fas fa-warehouse",
        "modulo.categoria": "fas fa-tags",
        "modulo.producto": "fas fa-boxes",
        "modulo.recepcion": "fas fa-truck-loading",
        "modulo.despacho": "fas fa-shipping-fast",
        "modulo.perfilusuario": "fas fa-user-shield",
        "modulo.trazabilidad": "fas fa-map-marked-alt",
    },
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "custom_css": "css/custom_admin.css?v=2.0",
    "order_with_apps": [
        "auth",
        "modulo",
    ],
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'